# Generated by Django 5.1.2 on 2024-10-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('aadhar', models.IntegerField(primary_key='aadhar', serialize=False)),
                ('dob', models.DateField()),
                ('passno', models.IntegerField()),
            ],
        ),
    ]
